"""empty message

Revision ID: 410d7b389408
Revises: 
Create Date: 2024-03-19 00:03:44.938761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410d7b389408'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('bathroom', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Property')
    # ### end Alembic commands ###
