"""empty message

Revision ID: 4dfb923caa1a
Revises: 410d7b389408
Create Date: 2024-03-19 12:39:12.345395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfb923caa1a'
down_revision = '410d7b389408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_bathroom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['photo'])
        batch_op.drop_column('bathroom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bathroom', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('photo')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('num_bathroom')

    # ### end Alembic commands ###
