"""empty message

Revision ID: b75c69c39fcb
Revises: 4dfb923caa1a
Create Date: 2024-03-19 15:17:39.807095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75c69c39fcb'
down_revision = '4dfb923caa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_bedroom', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.drop_column('num_bedroom')

    # ### end Alembic commands ###
